modLoader="javafml"
loaderVersion="[53,)"
license="CC BY-NC-ND 4.0"

[[mods]]
modId="itemborders"
version="${version}"
displayName="Item Borders"
displayURL="https://anthonyhilyard.com/"
updateJSONURL="https://mc-update-check.anthonyhilyard.com/513769"
logoFile="icon.png"
authors="Grend, Mat0u5"
description="Adds colored borders around items to indicate rarity."

[[dependencies.itemborders]]
	modId="forge"
	mandatory=true
	versionRange="[61,)"
	ordering="NONE"
	side="BOTH"

[[dependencies.itemborders]]
	modId="minecraft"
	mandatory=true
	versionRange="[1.21.11]"
	ordering="NONE"
	side="BOTH"

[[dependencies.itemborders]]
	modId="iceberg"
	mandatory=true
	versionRange="[1.4.0,)"
	ordering="AFTER"
	side="BOTH"

[[dependencies.itemborders]]
	modId="prism"
	mandatory=true
	versionRange="[1.1.0,)"
	ordering="AFTER"
	side="BOTH"

[[dependencies.itemborders]]
	modId="legendarytooltips"
	mandatory=false
	versionRange="[1.5.0,)"
	ordering="NONE"
	side="BOTH"