buildscript {
	repositories {
		gradlePluginPortal()
		maven { url "https://maven.architectury.dev/" }
		maven { url "https://maven.fabricmc.net/" }
		maven { url "https://files.minecraftforge.net/maven/" }
		mavenCentral()
	}
}

plugins {
	id 'io.github.goooler.shadow' version '8.1.7' apply false
	id 'dev.architectury.loom' version '1.7.416' apply false
	id 'architectury-plugin' version '3.4-SNAPSHOT' apply false
}

apply plugin: 'architectury-plugin'

architectury {
	minecraft = project.minecraftVersion
}

allprojects {
	group = rootProject.group
	version = rootProject.modVersion
}

subprojects {
	apply plugin: 'dev.architectury.loom'
	apply plugin: 'architectury-plugin'

	base {
		archivesName = "$rootProject.name-$rootProject.minecraftVersion-$project.name"
	}

	repositories {
		maven {
			name = "CurseMaven"
			url = "https://www.cursemaven.com"
		}
	}

	dependencies {
		minecraft "net.minecraft:minecraft:$rootProject.minecraftVersion"
		mappings loom.officialMojangMappings()

		// modImplementation "com.anthonyhilyard.iceberg:iceberg-common:1.2.1"
		// modImplementation "com.anthonyhilyard.prism:prism-fabric:1.0.7"
		// modImplementation "com.anthonyhilyard.legendarytooltips:legendarytooltips-common:1.4.7"
	}

	java {
		sourceCompatibility = JavaVersion.VERSION_21
		targetCompatibility = JavaVersion.VERSION_21
	}

	tasks.withType(JavaCompile).configureEach {
		it.options.release = 21
	}

	remapJar {
		destinationDirectory = file("$buildDir/../../output")
	}
}
