modLoader="javafml"
loaderVersion="[48,)"
license="CC BY-NC-ND 4.0"

[[mods]]
modId="itemborders"
version="${file.jarVersion}"
displayName="Item Borders"
displayURL="https://anthonyhilyard.com/"
updateJSONURL="https://mc-update-check.anthonyhilyard.com/513769"
logoFile="icon.png"
authors="Grend"
description="Adds colored borders around items to indicate rarity."

[[dependencies.itemborders]]
	modId="forge"
	mandatory=true
	versionRange="[48,)"
	ordering="NONE"
	side="BOTH"

[[dependencies.itemborders]]
	modId="minecraft"
	mandatory=true
	versionRange="[1.20.2,)"
	ordering="NONE"
	side="BOTH"

[[dependencies.itemborders]]
	modId="iceberg"
	mandatory=true
	versionRange="[1.1.16,)"
	ordering="NONE"
	side="BOTH"

[[dependencies.itemborders]]
	modId="prism"
	mandatory=true
	versionRange="[1.0.5,)"
	ordering="NONE"
	side="BOTH"