modLoader="javafml"
loaderVersion="[38,)"
license="CC BY-NC-ND 4.0"

[[mods]]
modId="itemborders"
version="${file.jarVersion}"
displayName="Item Borders"
displayURL="https://anthonyhilyard.com/"
updateJSONURL="https://mc-curse-update-checker.herokuapp.com/513769"
logoFile="icon.png"
authors="Grend"
description="Adds colored borders around items to indicate rarity."

[[dependencies.itemborders]]
	modId="forge"
	mandatory=true
	versionRange="[38,)"
	ordering="NONE"
	side="BOTH"

[[dependencies.itemborders]]
	modId="minecraft"
	mandatory=true
	versionRange="[1.18]"
	ordering="NONE"
	side="BOTH"

[[dependencies.itemborders]]
	modId="iceberg"
	mandatory=true
	versionRange="[1.0.30,)"
	ordering="NONE"
	side="BOTH"