modLoader="javafml"
loaderVersion="[36,)"
license="MIT"

[[mods]]
modId="itemborders"
version="${file.jarVersion}"
displayName="Item Borders"
displayURL="https://anthonyhilyard.com/"
updateJSONURL="https://mc-curse-update-checker.herokuapp.com/513769"
logoFile="icon.png"
authors="Grend"
description="Adds colored borders around items to indicate rarity."

[[dependencies.itemborders]]
	modId="forge"
	mandatory=true
	versionRange="[36,)"
	ordering="NONE"
	side="BOTH"

[[dependencies.itemborders]]
	modId="minecraft"
	mandatory=true
	versionRange="[1.16.5]"
	ordering="NONE"
	side="BOTH"

[[dependencies.itemborders]]
	modId="iceberg"
	mandatory=true
	versionRange="[1.0.8,)"
	ordering="NONE"
	side="BOTH"
